<?php

namespace Proxies\__CG__\FormArmorBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Formation extends \FormArmorBundle\Entity\Formation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'FormArmorBundle\\Entity\\Formation' . "\0" . 'id', '' . "\0" . 'FormArmorBundle\\Entity\\Formation' . "\0" . 'libelle', '' . "\0" . 'FormArmorBundle\\Entity\\Formation' . "\0" . 'niveau', '' . "\0" . 'FormArmorBundle\\Entity\\Formation' . "\0" . 'typeForm', '' . "\0" . 'FormArmorBundle\\Entity\\Formation' . "\0" . 'description', '' . "\0" . 'FormArmorBundle\\Entity\\Formation' . "\0" . 'diplomante', '' . "\0" . 'FormArmorBundle\\Entity\\Formation' . "\0" . 'duree', '' . "\0" . 'FormArmorBundle\\Entity\\Formation' . "\0" . 'coutrevient'];
        }

        return ['__isInitialized__', '' . "\0" . 'FormArmorBundle\\Entity\\Formation' . "\0" . 'id', '' . "\0" . 'FormArmorBundle\\Entity\\Formation' . "\0" . 'libelle', '' . "\0" . 'FormArmorBundle\\Entity\\Formation' . "\0" . 'niveau', '' . "\0" . 'FormArmorBundle\\Entity\\Formation' . "\0" . 'typeForm', '' . "\0" . 'FormArmorBundle\\Entity\\Formation' . "\0" . 'description', '' . "\0" . 'FormArmorBundle\\Entity\\Formation' . "\0" . 'diplomante', '' . "\0" . 'FormArmorBundle\\Entity\\Formation' . "\0" . 'duree', '' . "\0" . 'FormArmorBundle\\Entity\\Formation' . "\0" . 'coutrevient'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Formation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibelle($libelle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibelle', [$libelle]);

        return parent::setLibelle($libelle);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelle', []);

        return parent::getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    public function setNiveau($niveau)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNiveau', [$niveau]);

        return parent::setNiveau($niveau);
    }

    /**
     * {@inheritDoc}
     */
    public function getNiveau()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNiveau', []);

        return parent::getNiveau();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeForm($typeForm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeForm', [$typeForm]);

        return parent::setTypeForm($typeForm);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeForm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeForm', []);

        return parent::getTypeForm();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiplomante($diplomante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiplomante', [$diplomante]);

        return parent::setDiplomante($diplomante);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiplomante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiplomante', []);

        return parent::getDiplomante();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuree($duree)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuree', [$duree]);

        return parent::setDuree($duree);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuree()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuree', []);

        return parent::getDuree();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoutrevient($coutrevient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoutrevient', [$coutrevient]);

        return parent::setCoutrevient($coutrevient);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoutrevient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoutrevient', []);

        return parent::getCoutrevient();
    }

    /**
     * {@inheritDoc}
     */
    public function affichage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'affichage', []);

        return parent::affichage();
    }

}
